---

- hosts: all
  gather_facts: True
  user: root
  tasks:

  - name: get latest package list from plex
    uri:
      url: https://plex.tv/api/downloads/1.json
      method: GET
      return_content: yes
      status_code: 200
      body_format: json
    register: result

  - debug:
      msg: "{{ hostvars }}"

  - set_fact:
      os_distro: "{{ hostvars[ansible_hostname].ansible_facts.distribution }}"
      os_variety: "{{ hostvars[ansible_hostname].ansible_facts.distribution_file_variety | lower }}"
      os_architecture: "{{ hostvars[ansible_hostname].ansible_facts.architecture }}"

  - set_fact:
      url: "{{ result | to_json | from_json | json_query(\"json.computer.Linux.releases | [?contains(label,'\" + os_distro + \"')] | [?contains(url,'\" + os_architecture + \"')].url \") }}"

  - name: stop the pleax service
    service:
      name: plexmediaserver
      state: stopped

  - name: install the plex service if the OS is redhat based
    yum:
      name: "{{ url }}"
      state: present
    when: os_variety == "redhat"

  - name: install the plex service if the OS is ubuntu based
    apt:
      deb: "{{ url }}"
    when: os_variety == "ubuntu"

  - name: start the plex service after install
    service:
      name: plexmediaserver
      state: started


